name: Playwright Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest
    
    - name: Install dependencies
      run: bun install
      
    - name: Install Playwright browsers
      run: bunx playwright install --with-deps
      
    - name: Build application
      run: bun run build
    
    - name: Add executable permissions to server script
      run: chmod +x scripts/start-server.js
    
    - name: Start server with verification
      timeout-minutes: 2
      run: |
        bun scripts/start-server.js &
        echo "Server start script is running in background"
    
    - name: Run Playwright tests
      env:
        PLAYWRIGHT_TEST_BASE_URL: http://localhost:5173
      run: bunx playwright test
      
    - name: Upload test reports
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
