name: Workers Preview (PR)

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]

env:
  PREVIEW_NAME: iam-tools-pr-${{ github.event.pull_request.number }}

jobs:
  deploy-preview:
    # Skip preview deploys for forks: secrets are not available on forked PRs
    if: ${{ github.event_name == 'pull_request' && github.event.action != 'closed' && !github.event.pull_request.head.repo.fork }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
    concurrency:
      group: preview-${{ github.event.pull_request.number }}
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build frontend
        run: bun run build

      - name: Deploy preview Worker
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: deploy --name ${{ env.PREVIEW_NAME }}

  delete-preview:
    # Skip deletion for forks as well; forked PRs never deployed a preview
    if: ${{ github.event_name == 'pull_request' && github.event.action == 'closed' && !github.event.pull_request.head.repo.fork }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Delete preview Worker
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: delete --name ${{ env.PREVIEW_NAME }}
        continue-on-error: true
        